version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: marvel_snap
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"


